//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestTrump.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.7.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Provider=VFPOLEDB.1;Data Source=c:\\rest\\data")]
        public string cnnRestTrump {
            get {
                return ((string)(this["cnnRestTrump"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12/21/2018 11:26:00")]
        public string LastDate {
            get {
                return ((string)(this["LastDate"]));
            }
            set {
                this["LastDate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public string isActive {
            get {
                return ((string)(this["isActive"]));
            }
            set {
                this["isActive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12/21/2018 15:48:00")]
        public string LastDateUSe {
            get {
                return ((string)(this["LastDateUSe"]));
            }
            set {
                this["LastDateUSe"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool esPrecio3 {
            get {
                return ((bool)(this["esPrecio3"]));
            }
            set {
                this["esPrecio3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string KeyClave {
            get {
                return ((string)(this["KeyClave"]));
            }
            set {
                this["KeyClave"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ÚNICA CUENTA EN INSTAGRAM")]
        public string StartWith {
            get {
                return ((string)(this["StartWith"]));
            }
            set {
                this["StartWith"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool esPrioridadPrecio {
            get {
                return ((bool)(this["esPrioridadPrecio"]));
            }
            set {
                this["esPrioridadPrecio"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int TipoRedondeo {
            get {
                return ((int)(this["TipoRedondeo"]));
            }
            set {
                this["TipoRedondeo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int DecimalCalculo {
            get {
                return ((int)(this["DecimalCalculo"]));
            }
            set {
                this["DecimalCalculo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string appCnnStringName {
            get {
                return ((string)(this["appCnnStringName"]));
            }
            set {
                this["appCnnStringName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("400000")]
        public double LastDivisa {
            get {
                return ((double)(this["LastDivisa"]));
            }
            set {
                this["LastDivisa"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("000-000-000-000")]
        public string serialActivacion {
            get {
                return ((string)(this["serialActivacion"]));
            }
            set {
                this["serialActivacion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public decimal LastMargenGanancia {
            get {
                return ((decimal)(this["LastMargenGanancia"]));
            }
            set {
                this["LastMargenGanancia"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string appCadenaConexionHuesped {
            get {
                return ((string)(this["appCadenaConexionHuesped"]));
            }
            set {
                this["appCadenaConexionHuesped"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BaseDatosHuespedBD {
            get {
                return ((string)(this["BaseDatosHuespedBD"]));
            }
            set {
                this["BaseDatosHuespedBD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PasswordHuespedDB {
            get {
                return ((string)(this["PasswordHuespedDB"]));
            }
            set {
                this["PasswordHuespedDB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UsuarioHuespedBD {
            get {
                return ((string)(this["UsuarioHuespedBD"]));
            }
            set {
                this["UsuarioHuespedBD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string NombreHuespedBD {
            get {
                return ((string)(this["NombreHuespedBD"]));
            }
            set {
                this["NombreHuespedBD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool esServidorBD {
            get {
                return ((bool)(this["esServidorBD"]));
            }
            set {
                this["esServidorBD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string appDirDatosHostServer {
            get {
                return ((string)(this["appDirDatosHostServer"]));
            }
            set {
                this["appDirDatosHostServer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string appDirDatosHost {
            get {
                return ((string)(this["appDirDatosHost"]));
            }
            set {
                this["appDirDatosHost"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string appDirDatosHuesped {
            get {
                return ((string)(this["appDirDatosHuesped"]));
            }
            set {
                this["appDirDatosHuesped"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string appDirDatosHuespedServer {
            get {
                return ((string)(this["appDirDatosHuespedServer"]));
            }
            set {
                this["appDirDatosHuespedServer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c:\\rest\\data")]
        public string appDir_Datos {
            get {
                return ((string)(this["appDir_Datos"]));
            }
            set {
                this["appDir_Datos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("monitordolarvenzuela")]
        public string UsuarioInstagram {
            get {
                return ((string)(this["UsuarioInstagram"]));
            }
            set {
                this["UsuarioInstagram"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public decimal codigoMoneda {
            get {
                return ((decimal)(this["codigoMoneda"]));
            }
            set {
                this["codigoMoneda"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public string esLicenciaDemo {
            get {
                return ((string)(this["esLicenciaDemo"]));
            }
            set {
                this["esLicenciaDemo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string Usos {
            get {
                return ((string)(this["Usos"]));
            }
            set {
                this["Usos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public string MaxUsos {
            get {
                return ((string)(this["MaxUsos"]));
            }
            set {
                this["MaxUsos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public string MaxActualizaciones {
            get {
                return ((string)(this["MaxActualizaciones"]));
            }
            set {
                this["MaxActualizaciones"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public string esSQLServer {
            get {
                return ((string)(this["esSQLServer"]));
            }
            set {
                this["esSQLServer"] = value;
            }
        }
    }
}
